# Use official rails's rubocop configuration
require: rubocop-rspec
inherit_gem:
  rubocop-rails:
    - config/rails.yml
  rubocop-rspec:
    - config/default.yml

# apply rails specific cops
Rails:
  Enabled: true

# apply bundler specific cops
Bundler:
  Enabled: true

# override ruby version to 2.3.3
AllCops:
  TargetRubyVersion: 2.3.3

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
