version: '3'
services:
  api:
    build:
      context: .
      args:
        - env=production
        - bundle_opts=--without development test --deployment --clean
    image: qurancomapi_api:prod-latest
    environment:
      - SECRET_KEY_BASE=abcdefa

