version: '3'
services:
  api:
    build:
      context: .
      args:
        - env=development
        - bundle_opts=--without test
    image: qurancomapi_api:dev-latest
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://quran_dev:quran_password@postgres:5432/quran_db
      - ELASTICSEARCH_HOST=elasticsearch
      - SENTRY_DSN=
      - SECRET_KEY_BASE=abcdefa
    depends_on:
      - postgres
      - elasticsearch
  postgres:
    image: qurandb:v102
    ports:
      - "5342:5432"
  elasticsearch:
    image: quran/quran.com-elasticsearch:5.6.3
    ports:
      - "9300:9300"
      - "9200:9200"

