version: '3'
services:
  api:
    build:
      context: .
      args:
        - env=production
        - bundle_opts=--without development test --deployment --clean
    environment:
      - SENTRY_DSN=https://www.google.com
      - SECRET_KEY_BASE=abcdefa
